language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t valdrin-1986/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true valdrin-1986/react-test npm test -- --coverage

after_success:
  - docker build -t valdrin-1986/multi-client ./client
  - docker build -t valdrin-1986/multi-nginx ./nginx
  - docker build -t valdrin-1986/multi-server ./server
  - docker build -t valdrin-1986/multi-worker ./worker
